Задание 14 спринта
AnnaPustowit/java-shareit pull request #2
Opened 2023-05-07 20:59 UTC by AnnaPustowit

2023-05-08 18:18 UTC, db-exp requested changes

2023-05-08 18:18 UTC, db-exp commented on src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL UNIQUE,
очень много для email

2023-05-08 18:18 UTC, db-exp commented on src/main/resources/application.properties
>  spring.datasource.driverClassName=org.h2.Driver
можно разделить на два файла тест/прод

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +public interface ItemRepository extends JpaRepository<Item, Long> {
не хватает аннотации Repository

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +public interface CommentRepository extends JpaRepository<Comment, Long> {
не хватает аннотации Repository

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/dto/BookingJsonDto.java
> +public class BookingJsonDto {
Лучше назвать BookingInputDto

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
Не хватает аннотации Repository

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return toBookingDto(bookingRepository.findById(bookingId).filter(b -> Objects.equals(b.getBooker().getId(), userId) || Objects.equals(b.getItem().getOwner().getId(), userId)).orElseThrow(() -
лучше такие длинные выражения писать вот так
bookingRepository.findById(bookingId)
       .filter()
       ..orElseThrow()

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text == null || text.isBlank()) return Collections.emptyList();
можно эту проверку в сервис перенести

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
Не хватает аннотации Repository

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        return new ItemDto(item.getId(), item.getName(), item.getDescription(), item.getIsAvailable(), item.getOwner(), item.getRequest() != null ? item.getRequest().getId() : null);
давай выражение item.getRequest() != null ? в переменную вынесем или внутрь ItemDto
Можно еще создавать объект через Builder (есть Lombok аннотация Builder)

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() == null || itemDto.getName().isBlank() || itemDto.getDescription() == null || itemDto.getDescription().isBlank() || itemDto.getAvailable() == null) {
давай вот это вот все в dto перенесем)

2023-05-08 18:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        Optional<Booking> bookingLast = bookingList.stream().filter(booking -> Objects.equals(booking.getItem().getId(), itemsDto.getId())).sorted(Comparator.comparing(Booking::getEnd).reversed()).fi
давай вот такие длинные штуки отформатируем - очень сложно читать

2023-05-08 18:31 UTC, PustovitAnna commented on src/main/resources/schema.sql
> +    email VARCHAR(512) NOT NULL UNIQUE,
окей

2023-05-08 18:37 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/item/repository/ItemRepository.java
> +public interface ItemRepository extends JpaRepository<Item, Long> {
готово

2023-05-08 18:37 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/item/repository/CommentRepository.java
> +public interface CommentRepository extends JpaRepository<Comment, Long> {
готово

2023-05-08 18:39 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/booking/dto/BookingJsonDto.java
> +public class BookingJsonDto {
согласна

2023-05-08 18:40 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +public interface BookingRepository extends JpaRepository<Booking, Long> {
готово

2023-05-08 18:41 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return toBookingDto(bookingRepository.findById(bookingId).filter(b -> Objects.equals(b.getBooker().getId(), userId) || Objects.equals(b.getItem().getOwner().getId(), userId)).orElseThrow(() -
по код стайлу не пропускало из-за переноса строк

2023-05-08 18:42 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/user/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long> {
готово

2023-05-08 18:47 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +        if (text == null || text.isBlank()) return Collections.emptyList();
ага

2023-05-08 18:56 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (itemDto.getName() == null || itemDto.getName().isBlank() || itemDto.getDescription() == null || itemDto.getDescription().isBlank() || itemDto.getAvailable() == null) {
окей

2023-05-08 19:06 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        return new ItemDto(item.getId(), item.getName(), item.getDescription(), item.getIsAvailable(), item.getOwner(), item.getRequest() != null ? item.getRequest().getId() : null);
вынесла в переменную

2023-05-09 08:29 UTC, db-exp requested changes

2023-05-09 08:29 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        if (itemDto.getName() == null || itemDto.getName().isBlank() || itemDto.getDescription() == null || itemDto.getDescription().isBlank() || itemDto.getAvailable() == null) {
а вот это можеn все таки вынесем на уровне валидации в dto?

2023-05-09 10:01 UTC, AnnaPustowit commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +        if (itemDto.getName() == null || itemDto.getName().isBlank() || itemDto.getDescription() == null || itemDto.getDescription().isBlank() || itemDto.getAvailable() == null) {
можно, можно

2023-05-09 18:14 UTC, db-exp approved these changes

2023-05-09 20:39 UTC, merged