Первая версия тз 16
AnnaPustowit/java-shareit pull request #4
Opened 2023-06-03 10:18 UTC by AnnaPustowit

2023-06-04 19:51 UTC, db-exp requested changes

2023-06-04 19:51 UTC, db-exp commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
лучше использовать переменную из docker-compose через ${имя переменной}

2023-06-04 19:51 UTC, db-exp commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
лучше использовать переменную из docker-compose через ${имя переменной}

2023-06-04 22:19 UTC, AnnaPustowit commented on server/src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
хорошо, попробую

2023-06-04 22:19 UTC, AnnaPustowit commented on gateway/src/main/resources/application.properties
> +shareit-server.url=http://localhost:9090
хорошо

2023-06-05 10:20 UTC, db-exp approved these changes

2023-06-05 10:41 UTC, merged